[project]
name = "ldaca-web-app-workspace"
version = "0.0.1"
description = "LDaCA Web App Workspace"
requires-python = ">=3.14"
dependencies = [
    "ldaca-web-app-backend",
]

[tool.uv.workspace]
members = [
    "backend",
    "docworkspace",
    "ldaca-tabulator",
    "polars-text",
]

[tool.uv.sources]
ldaca-web-app-backend = { workspace = true }
