[project]
name = "ldaca-wordflow-workspace"
version = "0.5.6"
description = "LDaCA Wordflow Workspace"
requires-python = ">=3.14"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]
dependencies = ["ldaca-wordflow", "ldaca-loader"]

[tool.uv.sources]
ldaca-wordflow = { path = "./backend", editable = true }
ldaca-loader = { git = "https://github.com/Australian-Text-Analytics-Platform/ldaca-tabulator", branch = "ldaca_web_app_integration" }

[tool.pytest.ini_options]
testpaths = ["tests"]
