import { beforeEach, describe, expect, it, vi } from 'vitest';
import { saveBackendDownload, saveBlob, saveDataBlockDownload } from './download';

const mocks = vi.hoisted(() => ({
  invoke: vi.fn(),
  isTauri: vi.fn(),
  getCsrfToken: vi.fn(),
  revealItemInDir: vi.fn(),
  toast: { error: vi.fn(), success: vi.fn() },
}));

vi.mock('@tauri-apps/api/core', () => ({ invoke: mocks.invoke }));
vi.mock('@tauri-apps/plugin-opener', () => ({ revealItemInDir: mocks.revealItemInDir }));
vi.mock('@/lib/backend/csrfToken', () => ({ getCsrfToken: mocks.getCsrfToken }));
vi.mock('@/lib/isTauri', () => ({ isTauri: mocks.isTauri }));
vi.mock('sonner', () => ({ toast: mocks.toast }));

describe('desktop download boundary', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mocks.isTauri.mockReturnValue(true);
    mocks.getCsrfToken.mockReturnValue('desktop-csrf');
    mocks.invoke.mockImplementation(async (command: string) =>
      command === 'save_backend_download'
        ? {
            fullPath: '/Users/test/Documents/result.bin',
            omittedTabCount: 0,
            omittedAnalysisCount: 0,
          }
        : '/Users/test/Documents/result.bin',
    );
    URL.createObjectURL = vi.fn(() => 'blob:download');
    URL.revokeObjectURL = vi.fn();
  });

  it('sends webview-generated bytes to the native saver', async () => {
    await saveBlob(new Blob(['payload']), 'result.bin');

    expect(mocks.invoke).toHaveBeenCalledWith('save_generated_bytes', {
      filename: 'result.bin',
      bytes: new Uint8Array([112, 97, 121, 108, 111, 97, 100]),
    });
  });

  it('streams backend GET downloads without loading a browser blob', async () => {
    const loadBrowserDownload = vi.fn();

    const omissions = await saveBackendDownload(
      '/api/user-files/content?path=corpus.csv',
      'corpus.csv',
      loadBrowserDownload,
    );

    expect(loadBrowserDownload).not.toHaveBeenCalled();
    expect(mocks.invoke).toHaveBeenCalledWith('save_backend_download', {
      apiPath: '/api/user-files/content?path=corpus.csv',
      filename: 'corpus.csv',
    });
    expect(omissions).toEqual({ omittedTabCount: 0, omittedAnalysisCount: 0 });
  });

  it('uses only the explicit native Data Block export command for POST downloads', async () => {
    const loadBrowserDownload = vi.fn();

    await saveDataBlockDownload({
      workspaceId: '00000000-0000-0000-0000-000000000001',
      nodeIds: ['00000000-0000-0000-0000-000000000002'],
      format: 'parquet',
      filename: 'corpus.parquet',
      loadBrowserDownload,
    });

    expect(loadBrowserDownload).not.toHaveBeenCalled();
    expect(mocks.invoke).toHaveBeenCalledWith('save_data_block_export', {
      workspaceId: '00000000-0000-0000-0000-000000000001',
      nodeIds: ['00000000-0000-0000-0000-000000000002'],
      format: 'parquet',
      filename: 'corpus.parquet',
      csrfToken: 'desktop-csrf',
    });
  });

  it('treats a closed native Save As dialog as cancellation', async () => {
    mocks.invoke.mockResolvedValueOnce(null);
    const loadBrowserDownload = vi.fn();

    const result = await saveBackendDownload('/api/export', 'result.csv', loadBrowserDownload);

    expect(result).toBeNull();
    expect(loadBrowserDownload).not.toHaveBeenCalled();
    expect(mocks.toast.success).not.toHaveBeenCalled();
    expect(mocks.toast.error).not.toHaveBeenCalled();
  });

  it('reports the filename and path selected by the user', async () => {
    await saveBlob(new Blob(['payload']), 'suggested.bin');

    expect(mocks.toast.success).toHaveBeenCalledWith('Saved result.bin', {
      description: '/Users/test/Documents/result.bin',
      action: expect.objectContaining({ label: 'Show in folder' }),
    });
  });

  it('retains browser-owned downloads without invoking Rust', async () => {
    mocks.isTauri.mockReturnValue(false);
    const click = vi
      .spyOn(HTMLAnchorElement.prototype, 'click')
      .mockImplementation(() => undefined);
    const loadBrowserDownload = vi.fn().mockResolvedValue({
      blob: new Blob(['browser']),
      filename: 'server.csv',
      omittedTabCount: 2,
      omittedAnalysisCount: 3,
    });

    const omissions = await saveBackendDownload('/api/export', 'fallback.csv', loadBrowserDownload);

    expect(loadBrowserDownload).toHaveBeenCalledTimes(1);
    expect(click).toHaveBeenCalledTimes(1);
    expect(mocks.invoke).not.toHaveBeenCalled();
    expect(omissions).toEqual({ omittedTabCount: 2, omittedAnalysisCount: 3 });
  });
});
