# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
    # - name: Test
    #   run: npm test
    - name: Package production build (tar.gz)
      run: |
        rm -rf dist
        mkdir -p dist
        tar -czf dist/frontend-build.tar.gz -C build .
    - name: Upload build folder artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/build
        if-no-files-found: error
        retention-days: 14
    - name: Upload build tarball artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build-tar
        path: frontend/dist/frontend-build.tar.gz
        if-no-files-found: error
        retention-days: 14
