name: build-frontend
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: tar -C build -czf frontend-build.tar.gz .
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: frontend-latest
          files: frontend-build.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}